# Generated by Django 3.1.4 on 2021-01-01 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structures', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='chemdesk1',
            new_name='structures1',
        ),
    ]
