# Generated by Django 3.1.4 on 2021-01-02 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structures', '0002_auto_20210101_1358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='structures1',
            old_name='hotel_Main_Img',
            new_name='chemical_img',
        ),
    ]
