# Generated by Django 3.1.4 on 2021-01-01 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chemdesk', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hotel',
            new_name='chemdesk1',
        ),
    ]
